"""Headless browser reader with stealth context and instance reuse."""

from __future__ import annotations

import asyncio
import logging
import time
from contextlib import asynccontextmanager
from typing import Any

from .config import BROWSER_CONCURRENCY, DEFAULT_TIMEOUT
from .models import FetchAttempt, WebReadResult
from .utils import extract_text_bs4, extract_title_bs4, html_to_markdown, utc_now_iso

logger = logging.getLogger(__name__)

# Browser launch flags that reduce automation signals.
# Derived from general open-source knowledge on headless detection avoidance.
_LAUNCH_ARGS = [
    "--no-sandbox",
    "--disable-dev-shm-usage",
    "--disable-blink-features=AutomationControlled",
    "--disable-infobars",
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--disable-renderer-backgrounding",
    "--window-size=1280,720",
    "--disable-ipc-flooding-protection",
]

# Injects per-canvas pixel noise to disrupt canvas fingerprinting.
_CANVAS_NOISE_SCRIPT = """
(() => {
    const _getContext = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (type, ...args) {
        const ctx = _getContext.call(this, type, ...args);
        if (ctx && type === "2d") {
            const _getImageData = ctx.getImageData.bind(ctx);
            ctx.getImageData = function (...a) {
                const img = _getImageData(...a);
                for (let i = 0; i < img.data.length; i += 97) {
                    img.data[i] ^= Math.random() * 4 | 0;
                }
                return img;
            };
        }
        return ctx;
    };
})();
"""


def _get_ua() -> str:
    """Return a realistic Chrome UA string, generated by browserforge when available."""
    try:
        from browserforge.headers import HeaderGenerator

        hdrs = dict(HeaderGenerator(browser="chrome", os="windows").generate())
        return hdrs.get("User-Agent", "")
    except ImportError:
        pass
    return (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )


def _import_playwright():
    """Return async_playwright, preferring patchright over stock playwright."""
    try:
        from patchright.async_api import async_playwright

        return async_playwright
    except ImportError:
        pass
    try:
        from playwright.async_api import async_playwright

        return async_playwright
    except ImportError as exc:
        raise RuntimeError(
            "No browser driver found. "
            "Run: pip install 'web4agent[browser]' && playwright install chromium"
        ) from exc


# ── Browser manager ────────────────────────────────────────────────────────────


class _BrowserManager:
    """Shared browser instance with bounded page concurrency."""

    def __init__(self) -> None:
        self._playwright: Any = None
        self._browser: Any = None
        self._lock = asyncio.Lock()
        self._semaphore = asyncio.Semaphore(BROWSER_CONCURRENCY)

    async def _ensure_browser(self) -> Any:
        async with self._lock:
            if self._browser is None or not self._browser.is_connected():
                async_playwright = _import_playwright()
                self._playwright = await async_playwright().start()
                self._browser = await self._playwright.chromium.launch(
                    headless=True,
                    args=_LAUNCH_ARGS,
                )
                logger.debug("Browser launched")
        return self._browser

    @asynccontextmanager
    async def acquire_page(self, user_agent: str):
        async with self._semaphore:
            browser = await self._ensure_browser()
            context = await browser.new_context(
                user_agent=user_agent,
                java_script_enabled=True,
                viewport={"width": 1280, "height": 720},
                locale="en-US",
            )
            await context.add_init_script(_CANVAS_NOISE_SCRIPT)
            page = await context.new_page()
            try:
                yield page
            finally:
                await page.close()
                await context.close()

    async def close(self) -> None:
        async with self._lock:
            if self._browser:
                await self._browser.close()
                self._browser = None
            if self._playwright:
                await self._playwright.stop()
                self._playwright = None
            logger.debug("Browser closed")


_manager = _BrowserManager()


async def close_browser() -> None:
    """Explicitly close the shared browser instance."""
    await _manager.close()


# ── Main reader ────────────────────────────────────────────────────────────────


async def read_browser(
    url: str,
    wait_until: str = "networkidle",
    timeout: int = DEFAULT_TIMEOUT,
    screenshot: bool = False,
) -> WebReadResult:
    """
    Render a page with a headless browser and extract content from the live DOM.

    Uses patchright when installed (reduced bot-detection surface), falls back
    to stock Playwright. Browser instance is shared across calls; concurrency
    is capped at BROWSER_CONCURRENCY simultaneous pages.
    """
    start = time.monotonic()
    fetched_at = utc_now_iso()

    try:
        async with _manager.acquire_page(_get_ua()) as page:
            try:
                response = await page.goto(url, wait_until=wait_until, timeout=timeout * 1000)
                status_code = response.status if response else None

                # Trigger lazy-loaded content by scrolling incrementally.
                await page.evaluate(
                    """() => new Promise(resolve => {
                        let y = 0;
                        const tick = setInterval(() => {
                            window.scrollBy(0, 300);
                            y += 300;
                            if (y >= document.body.scrollHeight) {
                                clearInterval(tick);
                                resolve();
                            }
                        }, 80);
                    })"""
                )
                await asyncio.sleep(0.5)

                html = await page.content()
                final_url = page.url
                elapsed_ms = int((time.monotonic() - start) * 1000)

                try:
                    import trafilatura

                    text = trafilatura.extract(html, include_links=False)
                    meta = trafilatura.extract_metadata(html)
                    title = meta.title if meta else None
                except Exception:
                    text = title = None

                if not text:
                    text = extract_text_bs4(html)
                if not title:
                    title = extract_title_bs4(html)

                markdown = html_to_markdown(html)
                metadata: dict = {}

                if screenshot:
                    import base64

                    metadata["screenshot_b64"] = base64.b64encode(
                        await page.screenshot(full_page=True)
                    ).decode()

                success = bool(text) and (status_code is None or status_code < 400)

                return WebReadResult(
                    url=url,
                    final_url=final_url,
                    title=title,
                    text=text,
                    markdown=markdown,
                    html=html,
                    status_code=status_code,
                    success=success,
                    strategy_used="browser",
                    attempts=[
                        FetchAttempt(
                            strategy="browser",
                            success=success,
                            status_code=status_code,
                            elapsed_ms=elapsed_ms,
                        )
                    ],
                    fetched_at=fetched_at,
                    elapsed_ms=elapsed_ms,
                    metadata=metadata,
                )

            except Exception as exc:
                elapsed_ms = int((time.monotonic() - start) * 1000)
                error = f"{type(exc).__name__}: {exc}"
                logger.warning("read_browser error %s: %s", url, error)
                return WebReadResult(
                    url=url,
                    success=False,
                    error=error,
                    strategy_used="browser",
                    attempts=[
                        FetchAttempt(
                            strategy="browser",
                            success=False,
                            error=error,
                            elapsed_ms=elapsed_ms,
                        )
                    ],
                    fetched_at=fetched_at,
                    elapsed_ms=elapsed_ms,
                )

    except RuntimeError as exc:
        error = str(exc)
        return WebReadResult(
            url=url,
            success=False,
            error=error,
            strategy_used="browser",
            attempts=[FetchAttempt(strategy="browser", success=False, error=error)],
            fetched_at=fetched_at,
        )
